platform: x64
configuration: Release
image: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

install:
 - set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
 - git submodule update --init --recursive

build_script:
 - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
 - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
 - python setup.py build --qmake=C:\Qt\5.11.1\msvc2015_64\bin\qmake.exe --build-tests --ignore-git --jobs=1
